# site setting
theme: jekyll-theme-tactile
title: white stone
email: dev.gskim@gmail.com
timezone: Asia/Seoul
locale: "ko-KR"
description: "DevOps"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dev-gskim.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Site Author
author:
  name             : "gskim" 
  avatar           : "" # 프로필 이미지
  location         : "Republic of Korea"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"

# Defaults Post들에 적용될 기본 설정들
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

